@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package ommina.biomediversity.registry;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;