@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package ommina.biomediversity.worlddata;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;