@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package ommina.biomediversity.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;