@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package ommina.biomediversity.blocks.rainbarrel;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;