@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package ommina.biomediversity.worlddata.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;